# Generated by Django 4.2.4 on 2023-10-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
