# Generated by Django 4.2.4 on 2023-11-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0002_alter_activesession_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sftp_host', models.CharField(max_length=255)),
                ('sftp_port', models.IntegerField()),
                ('sftp_username', models.CharField(max_length=255)),
                ('sftp_password', models.CharField(max_length=255)),
                ('sftp_remote_path', models.CharField(max_length=255)),
                ('rss_url', models.URLField()),
                ('limit', models.IntegerField(default=2)),
                ('schedule_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
