# Generated by Django 4.2.4 on 2023-11-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0003_schedulingtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingtasks',
            name='schedule_time',
            field=models.CharField(max_length=200),
        ),
    ]
