# Generated by Django 4.2.4 on 2023-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0004_alter_schedulingtasks_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingtasks',
            name='intros',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schedulingtasks',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedulingtasks',
            name='outros',
            field=models.CharField(default='', max_length=200),
        ),
    ]
