# Generated by Django 4.2.4 on 2023-12-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0005_schedulingtasks_intros_schedulingtasks_is_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingtasks',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('everyhour', 'Every Hour'), ('monthly', 'Monthly'), ('onetime', 'Onetime')], default='onetime', max_length=20),
        ),
    ]
