# Generated by Django 4.2.4 on 2023-12-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0007_intros_outros'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingTasksWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sftp_host', models.CharField(max_length=255)),
                ('sftp_port', models.IntegerField()),
                ('sftp_username', models.CharField(max_length=255)),
                ('sftp_password', models.CharField(max_length=255)),
                ('sftp_remote_path', models.CharField(max_length=255)),
                ('schedule_time', models.CharField(max_length=200)),
                ('recurrence_type', models.CharField(choices=[('weekly', 'Weekly'), ('everyhour', 'Every Hour'), ('monthly', 'Monthly'), ('onetime', 'Onetime')], default='onetime', max_length=20)),
                ('intros', models.CharField(default='', max_length=200)),
                ('outros', models.CharField(default='', max_length=200)),
                ('is_pending', models.BooleanField(default=True)),
                ('city_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
