# Generated by Django 4.2.4 on 2023-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0009_schedulingtasksweatherbyzipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingtasksweatherbyzipcode',
            name='city_zipcode',
            field=models.IntegerField(),
        ),
    ]
