# Generated by Django 4.2.4 on 2023-12-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0010_alter_schedulingtasksweatherbyzipcode_city_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingtasksweatherbyzipcode',
            name='city_zipcode',
            field=models.CharField(max_length=200),
        ),
    ]
