# Generated by Django 4.2.4 on 2023-12-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0011_alter_schedulingtasksweatherbyzipcode_city_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingtasks',
            name='voice',
            field=models.CharField(choices=[('Neutral', 'Neutral'), ('Female', 'Female'), ('Male', 'Male'), ('Joanna', 'Joanna'), ('Matthew', 'Matthew'), ('Ivy', 'Ivy'), ('Justin', 'Justin'), ('Kendra', 'Kendra'), ('Kimberly', 'Kimberly'), ('Salli', 'Salli'), ('Joey', 'Joey'), ('Nicole', 'Nicole'), ('Russell', 'Russell'), ('Amy', 'Amy'), ('Brian', 'Brian'), ('Emma', 'Emma')], default='Neutral', max_length=2000),
        ),
    ]
