# Generated by Django 4.2.4 on 2023-12-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0014_schedulingtasksweatherbyzipcode_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingtasks',
            name='voice',
            field=models.CharField(choices=[('Joanna', 'Joanna'), ('Matthew', 'Matthew'), ('Ivy', 'Ivy'), ('Justin', 'Justin'), ('Kendra', 'Kendra'), ('Kimberly', 'Kimberly'), ('Salli', 'Salli'), ('Joey', 'Joey'), ('Nicole', 'Nicole'), ('Russell', 'Russell'), ('Amy', 'Amy'), ('Brian', 'Brian'), ('Emma', 'Emma'), ('Daniella', 'Daniella'), ('Ruth', 'Ruth'), ('Gregory', 'Gregory'), ('Kevin', 'Kevin'), ('Joey', 'Joey'), ('Stephan', 'Stephan')], default='Neutral', max_length=2000),
        ),
        migrations.AlterField(
            model_name='schedulingtasksweatherbyzipcode',
            name='voice',
            field=models.CharField(choices=[('Joanna', 'Joanna'), ('Matthew', 'Matthew'), ('Ivy', 'Ivy'), ('Justin', 'Justin'), ('Kendra', 'Kendra'), ('Kimberly', 'Kimberly'), ('Salli', 'Salli'), ('Joey', 'Joey'), ('Nicole', 'Nicole'), ('Russell', 'Russell'), ('Amy', 'Amy'), ('Brian', 'Brian'), ('Emma', 'Emma'), ('Daniella', 'Daniella'), ('Ruth', 'Ruth'), ('Gregory', 'Gregory'), ('Kevin', 'Kevin'), ('Joey', 'Joey'), ('Stephan', 'Stephan')], default='Neutral', max_length=2000),
        ),
    ]
