# Generated by Django 4.2.4 on 2023-12-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0016_alter_schedulingtasks_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingtasks',
            name='voice',
            field=models.CharField(choices=[('21m00Tcm4TlvDq8ikWAM', 'Rachel'), ('29vD33N1CtxCmqQRPOHJ', 'Drew'), ('2EiwWnXFnvU5JabPnv8n', 'Clyde'), ('AZnzlk1XvdvUeBnXmlld', 'Domi'), ('CYw3kZ02Hs0563khs1Fj', 'Dave'), ('D38z5RcWu1voky8WS1ja', 'Fin'), ('EXAVITQu4vr4xnSDxMaL', 'Sarah'), ('ErXwobaYiN019PkySvjV', 'Antoni'), ('GBv7mTt0atIp3Br8iCZE', 'Thomas'), ('IKne3meq5aSn9XLyUdCD', 'Charlie'), ('JBFqnCBsd6RMkjVDRZzb', 'George'), ('LcfcDJNUP1GQjkzn1xUU', 'Emily'), ('MF3mGyEYCl7XYWbV9V6O', 'Elli'), ('N2lVS1w4EtoT3dr4eOWO', 'Callum'), ('ODq5zmih8GrVes37Dizd', 'Patrick'), ('SOYHLrjzK2X1ezoPC6cr', 'Harry'), ('TX3LPaxmHKxFdv7VOQHJ', 'Liam'), ('ThT5KcBeYPX3keUQqHPh', 'Dorothy'), ('TxGEqnHWrfWFTfGW9XjX', 'Josh')], default='Neutral', max_length=2000),
        ),
        migrations.AlterField(
            model_name='schedulingtasksweatherbyzipcode',
            name='voice',
            field=models.CharField(choices=[('21m00Tcm4TlvDq8ikWAM', 'Rachel'), ('29vD33N1CtxCmqQRPOHJ', 'Drew'), ('2EiwWnXFnvU5JabPnv8n', 'Clyde'), ('AZnzlk1XvdvUeBnXmlld', 'Domi'), ('CYw3kZ02Hs0563khs1Fj', 'Dave'), ('D38z5RcWu1voky8WS1ja', 'Fin'), ('EXAVITQu4vr4xnSDxMaL', 'Sarah'), ('ErXwobaYiN019PkySvjV', 'Antoni'), ('GBv7mTt0atIp3Br8iCZE', 'Thomas'), ('IKne3meq5aSn9XLyUdCD', 'Charlie'), ('JBFqnCBsd6RMkjVDRZzb', 'George'), ('LcfcDJNUP1GQjkzn1xUU', 'Emily'), ('MF3mGyEYCl7XYWbV9V6O', 'Elli'), ('N2lVS1w4EtoT3dr4eOWO', 'Callum'), ('ODq5zmih8GrVes37Dizd', 'Patrick'), ('SOYHLrjzK2X1ezoPC6cr', 'Harry'), ('TX3LPaxmHKxFdv7VOQHJ', 'Liam'), ('ThT5KcBeYPX3keUQqHPh', 'Dorothy'), ('TxGEqnHWrfWFTfGW9XjX', 'Josh')], default='Neutral', max_length=2000),
        ),
    ]
