# Generated by Django 4.2.4 on 2024-01-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0019_schedulingtasksweatherbyzipcode_news_caster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscaster',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish')], max_length=100),
        ),
    ]
