# Generated by Django 4.2.4 on 2024-01-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0020_alter_newscaster_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingtasksweatherbyzipcode',
            name='language',
            field=models.CharField(default='', max_length=200),
        ),
    ]
