# Generated by Django 4.2.4 on 2024-01-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0021_schedulingtasksweatherbyzipcode_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingtasks',
            name='language',
            field=models.CharField(default='', max_length=200),
        ),
    ]
