# Generated by Django 4.2.4 on 2024-02-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0022_schedulingtasks_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscaster',
            name='sftp_host',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='newscaster',
            name='sftp_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='newscaster',
            name='sftp_port',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='newscaster',
            name='sftp_remote_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='newscaster',
            name='sftp_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
