# Generated by Django 4.2.4 on 2024-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0024_schedulingsongsmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingsongsmetadata',
            name='extra_edge',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='schedulingsongsmetadata',
            name='station_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
