# Generated by Django 4.2.4 on 2024-04-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0025_schedulingsongsmetadata_extra_edge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingsongsmetadata',
            name='extra_edge',
        ),
    ]
