# Generated by Django 4.2.4 on 2024-04-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0027_schedulingsongsmetadata_extra_edge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingsongsmetadata',
            name='extra_edge',
        ),
    ]
