# Generated by Django 4.2.4 on 2024-04-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0028_remove_schedulingsongsmetadata_extra_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingsongsmetadata',
            name='dynamicfolder',
            field=models.CharField(default='', max_length=255),
        ),
    ]
