# Generated by Django 4.2.4 on 2024-05-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0030_newscaster_shift_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscaster',
            name='shift_timing',
        ),
    ]
