# Generated by Django 4.2.4 on 2024-05-24 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('radioai', '0031_remove_newscaster_shift_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azuracast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sftp_host', models.CharField(max_length=100)),
                ('sftp_port', models.IntegerField()),
                ('sftp_username', models.CharField(max_length=100)),
                ('sftp_password', models.CharField(max_length=100)),
                ('remote_path', models.CharField(max_length=100)),
                ('voice', models.CharField(max_length=50)),
                ('news_caster', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('is_pending', models.BooleanField(default=True)),
            ],
        ),
    ]
